import type { Metadata } from "next";
import "./globals.css";

import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Toaster } from "sonner";
import { Suspense } from "react";
import BreadcrumbNav from "@/components/breadcrumpnav";
import { FormProvider } from "@/contexts/form-context";

export const metadata: Metadata = {
  title: "Multi Step Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <FormProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12 bg-gray-100">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1 cursor-pointer" />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  <Suspense fallback={<div>Loading breadcrumbs...</div>}>
                    <BreadcrumbNav />
                  </Suspense>
                </div>
              </header>
              <div className="flex flex-1 flex-col gap-4 p-8 pt-8">
                {children}
                <Toaster richColors position="bottom-right" />
              </div>
            </SidebarInset>
          </FormProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
